
project_id = "pmxnfpnnvtuuiedoxuxc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://utifinal.com"
additional_redirect_urls = ["https://utifinal.com"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true
enable_email_change_confirmations = true
enable_phone_confirmations = false
enable_phone_change_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_email_change_enabled = true
enable_reauthentication = true
max_frequency = "2s"

[auth.email.smtp]
host = "smtp.resend.com"
port = 587
user = "resend"
pass = "env(RESEND_API_KEY)"
admin_email = "admin@utifinal.com"
sender_name = "UTI Games"

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"
max_frequency = "5s"

[auth.external.apple]
enabled = false
client_id = ""
secret = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""

[auth.hooks.custom_access_token]
enabled = false
uri = ""

[auth.hooks.send_email]
enabled = true
uri = "https://pmxnfpnnvtuuiedoxuxc.supabase.co/functions/v1/send-custom-auth-email"

[auth.hooks.send_sms]
enabled = false
uri = ""

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = ""

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = {
  enabled = true
}

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions.send-custom-auth-email]
verify_jwt = false
