// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Load Supabase URL and Anon Key from environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Check if the environment variables are loaded
if (!SUPABASE_URL) {
  throw new Error("Supabase URL not found. Make sure VITE_SUPABASE_URL is set in your .env file.");
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase Anon Key not found. Make sure VITE_SUPABASE_ANON_KEY is set in your .env file.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);